language: c
compiler:
  - clang
  - gcc
before_install:
  - if [ "$CC" = "clang" ]; then export CXX="clang++"; else export CXX="g++"; fi
  - sudo add-apt-repository -y ppa:tmsz-kapela/valgrind-pmem
  - sudo apt-get update -qq
  - sudo apt-get install -y uuid-dev valgrind libunwind7-dev autoconf devscripts
  - cp src/test/testconfig.sh.example src/test/testconfig.sh
  - sudo mount -t tmpfs none /tmp -osize=4G
script:
  - if [ $MAKE_DPKG -eq 0 ]; then make cstyle && make -j2 USE_LIBUNWIND=1 && make -j2 test USE_LIBUNWIND=1 && make check && make DESTDIR=/tmp source; fi
  - if [ $MAKE_DPKG -eq 1 ]; then make -j2 dpkg; fi
env:
  - MAKE_DPKG=0 EXTRA_CFLAGS=-DUSE_VALGRIND
  - MAKE_DPKG=0 EXTRA_CFLAGS=
  - MAKE_DPKG=1
